name: Update Fun Stats

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🐍 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spacy textstat textblob wordcloud scikit-learn
          python -m textblob.download_corpora
          python -m spacy download en_core_web_sm

      - name: 📁 List Files for Debugging
        run: |
          ls -la
          find . -name "*.html"

      - name: 🧠 Run Stats Script
        run: python generate_stats.py

      - name: 🖼️ Display Output Files
        run: |
          cat stats.html || echo "❌ stats.html not found"
          ls -l wordcloud.png || echo "❌ wordcloud.png not found"

      - name: 🚀 Commit Updated Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stats.html wordcloud.png
          git diff --cached --quiet || git commit -m "🤖 Auto-update stats"
          git pull --rebase
          git push

      - name: 📦 Upload stats.html (Artifact for Debugging)
        uses: actions/upload-artifact@v4
        with:
          name: stats
          path: stats.html
