name: Update Fun Stats
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pytz  # Only if you use timezone features
      - run: python generate_stats.py
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stats.html
          git commit -m "🤖 Auto-update fun stats" || echo "No changes"
          git push
