name: Update Fun Stats
on:
  workflow_dispatch:  # Allows manual runs
  schedule:
    - cron: '0 12 * * *'  # Daily at 12 PM UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:  # Minimal permissions
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python generate_stats.py
      - name: Commit Stats
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add stats.html
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto-update stats"
          git push
